"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Activity, ArrowUp, Headphones, Languages, LoaderCircle, Phone, PhoneOff, Radio, Sparkles } from "lucide-react";
import { API_URL, api } from "@/lib/api";
import { useAuthStore } from "@/stores/auth-store";
import type { CallEvent } from "@/types/api";
import { Button } from "@/components/ui/button";

export default function CallsPage(){
  const token=useAuthStore(s=>s.accessToken)!,socket=useRef<WebSocket|null>(null),sequence=useRef(0);
  const [status,setStatus]=useState<"idle"|"connecting"|"live"|"ended">("idle"),[source,setSource]=useState("auto"),[target,setTarget]=useState("en"),[draft,setDraft]=useState(""),[events,setEvents]=useState<CallEvent[]>([]),[error,setError]=useState("");
  const history=useQuery({queryKey:["call-sessions"],queryFn:()=>api.callSessions(token)});
  useEffect(()=>()=>socket.current?.close(),[]);
  async function start(){setStatus("connecting");setError("");setEvents([]);try{const grant=await api.callTicket(source,target,token),base=new URL(API_URL),url=`${base.protocol==="https:"?"wss":"ws"}://${base.host}${grant.websocket_path}?ticket=${encodeURIComponent(grant.ticket)}`;const ws=new WebSocket(url);socket.current=ws;ws.onmessage=(message)=>{const event=JSON.parse(message.data) as CallEvent;setEvents(current=>[...current,event]);if(event.type==="session_ready")setStatus("live");if(event.type==="call_summary"){setStatus("ended");history.refetch()}};ws.onerror=()=>setError("The real-time connection could not be established.");ws.onclose=()=>setStatus(current=>current==="live"?"ended":current)}catch(reason){setStatus("idle");setError(reason instanceof Error?reason.message:"Unable to start call")}}
  function sendTurn(event?:FormEvent){event?.preventDefault();if(!draft.trim()||socket.current?.readyState!==WebSocket.OPEN)return;socket.current.send(JSON.stringify({type:"text_turn",speaker:"customer",text:draft.trim()}));setDraft("")}
  function simulateAudio(){if(socket.current?.readyState!==WebSocket.OPEN)return;const phrase="Muraho, mfite ikibazo kandi ndashaka ubufasha";socket.current.send(JSON.stringify({type:"audio_chunk",sequence:sequence.current++,audio:btoa("simulated-pcm-audio")}));socket.current.send(JSON.stringify({type:"end_audio"}));socket.current.send(JSON.stringify({type:"text_turn",speaker:"customer",text:phrase}))}
  function end(){socket.current?.send(JSON.stringify({type:"end_call"}))}
  const visible=events.filter(event=>["final_transcript","translation","reply_suggestion","sentiment_cue","call_summary","error","audio_buffered"].includes(event.type));
  return <section className="calls-page"><header className="calls-head"><div><span className="kicker">REAL-TIME FOUNDATION</span><h1>Be present in the call.<br/><em>EVA follows the meaning.</em></h1></div><div className={`live-orb ${status}`}><Radio/><span>{status}</span></div></header>
    <div className="calls-grid"><div className="call-console"><div className="call-toolbar"><label>Heard language<select disabled={status==="live"} value={source} onChange={e=>setSource(e.target.value)}><option value="auto">Detect automatically</option><option value="en">English</option><option value="rw">Kinyarwanda</option></select></label><Languages/><label>Assist in<select disabled={status==="live"} value={target} onChange={e=>setTarget(e.target.value)}><option value="en">English</option><option value="rw">Kinyarwanda</option></select></label></div>{status==="idle"?<div className="call-welcome"><div><Headphones/></div><h2>Start a simulated assistance session</h2><p>This internal client verifies EVA’s secure WebSocket protocol before telephony integration. It sends no microphone audio.</p><Button onClick={start}><Phone/> Start session</Button></div>:<div className="call-live"><div className="call-state"><Activity/><div><strong>{status==="connecting"?"Connecting securely…":status==="live"?"Assistance is live":"Session complete"}</strong><small>Bounded audio · private session · no recording retained</small></div>{status==="live"&&<Button size="sm" className="end-call" onClick={end}><PhoneOff/> End</Button>}</div><div className="event-stream">{!visible.length&&<div className="waiting"><LoaderCircle className={status==="connecting"?"spin":""}/><p>Waiting for the first customer turn…</p></div>}{visible.map((event,index)=><EventCard key={`${event.type}-${index}`} event={event}/>)}</div>{status==="live"&&<><form className="call-input" onSubmit={sendTurn}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Type a simulated customer turn…"/><Button size="icon" aria-label="Send simulated turn"><ArrowUp/></Button></form><button className="simulate-audio" onClick={simulateAudio}><Radio/> Send simulated Kinyarwanda audio turn</button></>}</div>}{error&&<p className="form-error">{error}</p>}</div>
      <aside className="call-side"><div className="section-number">PROTOCOL EVENTS</div><h2>One shared intelligence layer</h2><p>Text simulation exercises the same language detection, translation, reply guidance, sentiment cues, and wrap-up services intended for streamed speech.</p><ul><li><span/>Final transcript</li><li><span/>Live translation</li><li><span/>Professional reply</li><li><span/>Sentiment cue</li><li><span/>Summary & actions</li></ul><div className="session-count"><strong>{history.data?.length||0}</strong><span>saved sessions<br/>owned by you</span></div></aside></div>
  </section>
}

function EventCard({event}:{event:CallEvent}){const labels:Record<string,string>={final_transcript:"CUSTOMER",translation:"TRANSLATION",reply_suggestion:"SUGGESTED REPLY",sentiment_cue:"SENTIMENT",call_summary:"WRAP-UP",error:"SYSTEM",audio_buffered:"AUDIO BUFFER"};return <article className={`event-card ${event.type}`}><span>{labels[event.type]||event.type}</span>{event.type==="reply_suggestion"&&<Sparkles/>}<p>{event.text||event.summary||event.message||event.cue}</p>{event.action_items?.length?<ul>{event.action_items.map(item=><li key={item}>{item}</li>)}</ul>:null}</article>}
