"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { BookOpen, LoaderCircle, Play, Sparkles } from "lucide-react";
import { api } from "@/lib/api";
import { useAuthStore } from "@/stores/auth-store";
import type { StudyArtifact } from "@/types/api";
import { Button } from "@/components/ui/button";

const types = [["summary","Summary"],["key_points","Key points"],["short_notes","Short notes"],["explanation","Explain"],["quiz","Quiz"],["flashcards","Flashcards"],["vocabulary","Vocabulary"],["synonyms","Synonyms"],["translation","Translate"]];
const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export default function StudyPage() {
  const token = useAuthStore((state) => state.accessToken)!;
  const [artifactType,setArtifactType]=useState("summary"), [text,setText]=useState(""), [documentId,setDocumentId]=useState(""), [language,setLanguage]=useState("en"), [difficulty,setDifficulty]=useState("intermediate"), [length,setLength]=useState("medium"), [audioUrl,setAudioUrl]=useState<string|null>(null);
  const documents = useQuery({ queryKey:["documents","study"], queryFn:()=>api.documents(token) });
  const generate = useMutation({ mutationFn:()=>api.generateStudy({artifact_type:artifactType,text:text.trim()||null,document_id:documentId||null,language,difficulty,audience:"student",length,count:5},token) });
  const speak = useMutation({ mutationFn:async(content:string)=>{ const queued=await api.synthesize(content,language,token); for(let attempt=0;attempt<30;attempt++){ await delay(1000); const job=await api.speechJob(queued.job_id,token); if(job.status==="failed") throw new Error(job.error_message||"Speech generation failed"); if(job.status==="completed"&&job.result.attachment_id){ return URL.createObjectURL(await api.speechAudio(job.result.attachment_id,token)); } } throw new Error("Speech is still processing. Try again shortly."); }, onSuccess:(url)=>setAudioUrl(url) });
  useEffect(()=>()=>{if(audioUrl)URL.revokeObjectURL(audioUrl)},[audioUrl]);
  const readable=useMemo(()=>generate.data?artifactText(generate.data):"",[generate.data]);
  function submit(event:FormEvent){event.preventDefault();if(text.trim()||documentId)generate.mutate();}
  return <section className="study-page"><header className="study-head"><div><span className="kicker">EVA STUDY STUDIO</span><h1>Turn source material<br/>into <em>understanding.</em></h1></div><div className="study-seal"><BookOpen/><span>Learn in<br/>your language</span></div></header>
    <div className="study-layout"><form className="study-controls" onSubmit={submit}><label>What should EVA create?<div className="type-picker">{types.map(([value,label])=><button type="button" key={value} className={artifactType===value?"selected":""} onClick={()=>setArtifactType(value)}>{label}</button>)}</div></label><label>Source text<textarea rows={8} value={text} onChange={(event)=>setText(event.target.value)} placeholder="Paste notes, a topic, or a term…"/></label><div className="or-rule"><span>OR USE A DOCUMENT</span></div><label>Ready document<select value={documentId} onChange={(event)=>setDocumentId(event.target.value)}><option value="">Choose a document</option>{documents.data?.items.filter((item)=>item.status==="ready").map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><div className="control-row"><label>Language<select value={language} onChange={(e)=>setLanguage(e.target.value)}><option value="en">English</option><option value="rw">Kinyarwanda</option></select></label><label>Difficulty<select value={difficulty} onChange={(e)=>setDifficulty(e.target.value)}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><label>Length<select value={length} onChange={(e)=>setLength(e.target.value)}><option value="short">Short</option><option value="medium">Medium</option><option value="long">Long</option></select></label></div><Button disabled={generate.isPending||(!text.trim()&&!documentId)}>{generate.isPending?<LoaderCircle className="spin"/>:<Sparkles/>} Generate study material</Button>{generate.error&&<p className="form-error" role="alert">{generate.error.message}</p>}</form>
      <div className="study-result">{!generate.data?<div className="study-empty"><span>01</span><BookOpen/><h2>Your learning material<br/>will appear here.</h2><p>Choose a format, provide a source, and let EVA structure the next step.</p></div>:<Artifact artifact={generate.data}/>} {generate.data&&<div className="read-bar"><Button variant="outline" onClick={()=>speak.mutate(readable)} disabled={speak.isPending}>{speak.isPending?<LoaderCircle className="spin"/>:<Play/>} Read aloud</Button>{audioUrl&&<audio controls autoPlay src={audioUrl}/>} {speak.error&&<small>{speak.error.message}</small>}</div>}</div></div>
  </section>;
}

function Artifact({artifact}:{artifact:StudyArtifact}){const c=artifact.content;return <article className="artifact"><header><span>{artifact.artifact_type.replaceAll("_"," ")}</span><h2>{artifact.title}</h2><p>{artifact.difficulty} · {artifact.language==="rw"?"Kinyarwanda":"English"}</p></header>{c.summary&&<p className="artifact-lead">{c.summary}</p>}{c.explanation&&<p className="artifact-lead">{c.explanation}</p>}{c.translated_text&&<p className="artifact-lead">{c.translated_text}</p>}{!!c.key_points.length&&<ul>{c.key_points.map((x,i)=><li key={i}>{x}</li>)}</ul>}{!!c.notes.length&&<ul>{c.notes.map((x,i)=><li key={i}>{x}</li>)}</ul>}{!!c.synonyms.length&&<div className="word-chips">{c.synonyms.map(x=><span key={x}>{x}</span>)}</div>}{c.quiz.map((x,i)=><section className="quiz-item" key={i}><span>QUESTION {i+1}</span><h3>{x.question}</h3>{x.options.map(option=><p key={option}>○ {option}</p>)}<details><summary>Show answer</summary><strong>{x.answer}</strong><p>{x.explanation}</p></details><Cites ids={x.source_ids}/></section>)}<div className="flash-grid">{c.flashcards.map((x,i)=><section key={i}><span>FRONT</span><h3>{x.front}</h3><hr/><span>BACK</span><p>{x.back}</p><Cites ids={x.source_ids}/></section>)}</div>{c.vocabulary.map((x,i)=><section className="vocab" key={i}><h3>{x.term}</h3><p>{x.definition}</p>{x.synonyms.length>0&&<small>Synonyms: {x.synonyms.join(", ")}</small>}<Cites ids={x.source_ids}/></section>)}{artifact.source_refs.length>0&&<details className="sources"><summary>View {artifact.source_refs.length} source passages</summary>{artifact.source_refs.map(ref=><p key={ref.id}><strong>[{ref.id}]</strong> {ref.excerpt} {ref.page_number&&<small>p. {ref.page_number}</small>}</p>)}</details>}</article>}
function Cites({ids}:{ids:string[]}){return ids.length?<div className="cites">{ids.map(id=><span key={id}>[{id}]</span>)}</div>:null}
function artifactText(a:StudyArtifact){const c=a.content;return [c.summary,c.explanation,c.translated_text,...c.key_points,...c.notes,...c.synonyms,...c.quiz.flatMap(x=>[x.question,x.answer,x.explanation]),...c.flashcards.flatMap(x=>[x.front,x.back]),...c.vocabulary.flatMap(x=>[x.term,x.definition])].filter(Boolean).join(". ").slice(0,20000)}
