"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookOpen, Download, FileUp, Library, LoaderCircle, Play, Sparkles, Trash2 } from "lucide-react";
import { api } from "@/lib/api";
import { useAuthStore } from "@/stores/auth-store";
import type { StudyArtifact } from "@/types/api";
import { Button } from "@/components/ui/button";

const types = [["summary","Summary"],["key_points","Key points"],["short_notes","Short notes"],["explanation","Explain"],["quiz","Questions"],["flashcards","Flashcards"],["vocabulary","Vocabulary"],["synonyms","Synonyms"],["translation","Translate"]];
const delay = (ms:number) => new Promise(resolve => setTimeout(resolve,ms));

export default function StudyPage(){
  const token=useAuthStore(state=>state.accessToken)!, queryClient=useQueryClient(), fileInput=useRef<HTMLInputElement>(null);
  const [artifactType,setArtifactType]=useState("summary"),[text,setText]=useState(""),[documentId,setDocumentId]=useState(""),[language,setLanguage]=useState("en"),[difficulty,setDifficulty]=useState("intermediate"),[length,setLength]=useState("medium"),[count,setCount]=useState(5),[voiceId,setVoiceId]=useState(""),[audioUrl,setAudioUrl]=useState<string|null>(null),[active,setActive]=useState<StudyArtifact|null>(null),[notice,setNotice]=useState("");
  const documents=useQuery({queryKey:["documents","study"],queryFn:()=>api.documents(token)});
  const voices=useQuery({queryKey:["voice-profiles"],queryFn:()=>api.voiceProfiles(token)});
  const library=useQuery({queryKey:["study-artifacts"],queryFn:()=>api.studyArtifacts(token)});
  const generate=useMutation({mutationFn:()=>api.generateStudy({artifact_type:artifactType,text:text.trim()||null,document_id:documentId||null,language,difficulty,audience:"student",length,count},token),onSuccess:(artifact)=>{setActive(artifact);setNotice("Saved automatically to My Study Library.");queryClient.invalidateQueries({queryKey:["study-artifacts"]})}});
  const upload=useMutation({mutationFn:async(file:File)=>{const result=await api.uploadDocument(file,token);setNotice(`Processing ${file.name}…`);for(let i=0;i<120;i++){await delay(1000);const job=await api.documentJob(result.job_id,token);if(job.status==="completed")return result.document;if(job.status==="failed")throw new Error(job.error_message||"Document processing failed")}throw new Error("Document processing is taking longer than expected")},onSuccess:(document)=>{setDocumentId(document.id);setText("");setNotice(`${document.title} is ready and selected.`);queryClient.invalidateQueries({queryKey:["documents","study"]})},onError:error=>setNotice(error.message)});
  const speak=useMutation({mutationFn:async(content:string)=>{const queued=await api.synthesize(content,active?.language||language,token,voiceId||undefined);for(let i=0;i<120;i++){await delay(1000);const job=await api.speechJob(queued.job_id,token);if(job.status==="failed")throw new Error(job.error_message||"Speech generation failed");if(job.status==="completed"&&job.result.attachment_id)return {url:URL.createObjectURL(await api.speechAudio(job.result.attachment_id,token)),engine:String(job.result.engine||"")}}throw new Error("Speech generation is taking longer than expected. Please try again.")},onMutate:()=>{if(audioUrl){URL.revokeObjectURL(audioUrl);setAudioUrl(null)}setNotice("")},onSuccess:result=>{setAudioUrl(result.url);if(voiceId&&result.engine!=="xtts_v2")setNotice("Your lecturer voice engine is not enabled yet, so EVA used the default reading voice.")}});
  const remove=useMutation({mutationFn:(id:string)=>api.deleteStudyArtifact(id,token),onSuccess:(_,id)=>{if(active?.id===id)setActive(null);queryClient.invalidateQueries({queryKey:["study-artifacts"]})}});
  useEffect(()=>()=>{if(audioUrl)URL.revokeObjectURL(audioUrl)},[audioUrl]);
  const readable=useMemo(()=>active?artifactText(active):"",[active]);
  function submit(event:FormEvent){event.preventDefault();if(text.trim()||documentId)generate.mutate()}
  return <section className="study-page"><header className="study-head"><div><span className="kicker">EVA STUDY STUDIO</span><h1>Turn your modules<br/>into <em>understanding.</em></h1><p>Upload private notes, learn in English or Kinyarwanda, and keep every result in your own library.</p></div><div className="study-seal"><BookOpen/><span>Your private<br/>study library</span></div></header>
    <div className="study-workbench"><form className="study-controls" onSubmit={submit}><label>Upload notes or a module<Button type="button" variant="outline" onClick={()=>fileInput.current?.click()} disabled={upload.isPending}>{upload.isPending?<LoaderCircle className="spin"/>:<FileUp/>} {upload.isPending?"Processing…":"Choose PDF, Word, text, or image"}</Button><input ref={fileInput} className="hidden-file-input" type="file" accept=".pdf,.docx,.txt,.png,.jpg,.jpeg,.tif,.tiff" onChange={event=>{const file=event.target.files?.[0];if(file)upload.mutate(file);event.target.value=""}}/></label><div className="or-rule"><span>OR PASTE NOTES</span></div><label>Source text<textarea rows={6} value={text} onChange={event=>{setText(event.target.value);if(event.target.value)setDocumentId("")}} placeholder="Paste notes, a topic, or a word…"/></label><label>My ready documents<select value={documentId} onChange={event=>{setDocumentId(event.target.value);if(event.target.value)setText("")}}><option value="">Choose from your library</option>{documents.data?.items.filter(item=>item.status==="ready").map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>What should EVA create?<div className="type-picker">{types.map(([value,label])=><button type="button" key={value} className={artifactType===value?"selected":""} onClick={()=>setArtifactType(value)}>{label}</button>)}</div></label><div className="control-row"><label>Output language<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="en">English</option><option value="rw">Kinyarwanda</option></select></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><label>Length<select value={length} onChange={e=>setLength(e.target.value)}><option value="short">Short</option><option value="medium">Medium</option><option value="long">Long</option></select></label></div>{["quiz","flashcards","vocabulary"].includes(artifactType)&&<label>Number of items<input type="number" min="1" max="20" value={count} onChange={e=>setCount(Math.max(1,Math.min(20,Number(e.target.value))))}/></label>}<Button disabled={generate.isPending||(!text.trim()&&!documentId)}>{generate.isPending?<LoaderCircle className="spin"/>:<Sparkles/>} Generate study material</Button>{notice&&<p className="study-notice">{notice}</p>}{generate.error&&<p className="form-error">{generate.error.message}</p>}</form>
      <main className="study-result">{!active?<div className="study-empty"><span>01</span><BookOpen/><h2>Your learning material<br/>will appear here.</h2><p>Summarize, explain, translate, build questions, discover vocabulary and synonyms, or create revision cards.</p></div>:<><Artifact artifact={active}/><div className="study-tools"><label>Reading voice<select value={voiceId} onChange={e=>setVoiceId(e.target.value)}><option value="">EVA default voice</option>{voices.data?.items.filter(v=>v.status==="active").map(v=><option key={v.id} value={v.id}>{v.name} (lecturer voice)</option>)}</select></label><Button variant="outline" onClick={()=>speak.mutate(readable)} disabled={speak.isPending}>{speak.isPending?<LoaderCircle className="spin"/>:<Play/>} Read aloud</Button><ExportMenu artifact={active}/>{audioUrl&&<audio controls autoPlay src={audioUrl}/>}</div>{speak.error&&<p className="form-error">{speak.error.message}</p>}</>}</main>
      <aside className="study-library"><div className="library-title"><Library/><div><strong>My Study Library</strong><small>{library.data?.total||0} saved items</small></div></div>{library.isLoading&&<p>Loading…</p>}{library.data?.items.map(item=><button className={`library-item ${active?.id===item.id?"active":""}`} key={item.id} onClick={()=>setActive(item)}><span><strong>{item.title}</strong><small>{item.artifact_type.replaceAll("_"," ")} · {new Date(item.created_at).toLocaleDateString()}</small></span><Trash2 onClick={event=>{event.stopPropagation();if(confirm("Delete this study item?"))remove.mutate(item.id)}}/></button>)}</aside></div>
  </section>
}

function Artifact({artifact}:{artifact:StudyArtifact}){const c=artifact.content;return <article className="artifact"><header><span>{artifact.artifact_type.replaceAll("_"," ")}</span><h2>{artifact.title}</h2><p>{artifact.difficulty} · {artifact.language==="rw"?"Kinyarwanda":"English"}</p></header>{c.summary&&<p className="artifact-lead">{c.summary}</p>}{c.explanation&&<p className="artifact-lead">{c.explanation}</p>}{c.translated_text&&<p className="artifact-lead">{c.translated_text}</p>}{!!c.key_points.length&&<ul>{c.key_points.map((x,i)=><li key={i}>{x}</li>)}</ul>}{!!c.notes.length&&<ul>{c.notes.map((x,i)=><li key={i}>{x}</li>)}</ul>}{!!c.synonyms.length&&<div className="word-chips">{c.synonyms.map(x=><span key={x}>{x}</span>)}</div>}{c.quiz.map((x,i)=><section className="quiz-item" key={i}><span>QUESTION {i+1}</span><h3>{x.question}</h3>{x.options.map(option=><p key={option}>○ {option}</p>)}<details><summary>Show answer</summary><strong>{x.answer}</strong><p>{x.explanation}</p></details><Cites ids={x.source_ids}/></section>)}<div className="flash-grid">{c.flashcards.map((x,i)=><section key={i}><span>FRONT</span><h3>{x.front}</h3><hr/><span>BACK</span><p>{x.back}</p><Cites ids={x.source_ids}/></section>)}</div>{c.vocabulary.map((x,i)=><section className="vocab" key={i}><h3>{x.term}</h3><p>{x.definition}</p>{x.synonyms.length>0&&<small>Synonyms: {x.synonyms.join(", ")}</small>}{x.translation&&<p>Translation: {x.translation}</p>}<Cites ids={x.source_ids}/></section>)}{artifact.source_refs.length>0&&<details className="sources"><summary>View {artifact.source_refs.length} source passages</summary>{artifact.source_refs.map(ref=><p key={ref.id}><strong>[{ref.id}]</strong> {ref.excerpt} {ref.page_number&&<small>p. {ref.page_number}</small>}</p>)}</details>}</article>}
function Cites({ids}:{ids:string[]}){return ids.length?<div className="cites">{ids.map(id=><span key={id}>[{id}]</span>)}</div>:null}
function artifactText(a:StudyArtifact){const c=a.content;return [c.summary,c.explanation,c.translated_text,...c.key_points,...c.notes,...c.synonyms,...c.quiz.flatMap(x=>[x.question,x.answer,x.explanation]),...c.flashcards.flatMap(x=>[x.front,x.back]),...c.vocabulary.flatMap(x=>[x.term,x.definition,x.synonyms.join(", ")])].filter(Boolean).join("\n\n").slice(0,20000)}
function safeName(value:string){return value.replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase()||"eva-study"}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function tableRows(a:StudyArtifact):string[][]{const c=a.content;if(c.quiz.length)return [["Question","Options","Answer","Explanation"],...c.quiz.map(x=>[x.question,x.options.join(" | "),x.answer,x.explanation])];if(c.flashcards.length)return [["Front","Back"],...c.flashcards.map(x=>[x.front,x.back])];if(c.vocabulary.length)return [["Term","Definition","Synonyms","Translation"],...c.vocabulary.map(x=>[x.term,x.definition,x.synonyms.join(", "),x.translation||""])];return []}
function ExportMenu({artifact}:{artifact:StudyArtifact}){const name=safeName(artifact.title),rows=tableRows(artifact);async function pdf(){const {jsPDF}=await import("jspdf");const doc=new jsPDF();doc.setFontSize(18);doc.text(artifact.title,15,18);doc.setFontSize(10);const lines=doc.splitTextToSize(artifactText(artifact),180);let y=28;for(const line of lines){if(y>282){doc.addPage();y=15}doc.text(line,15,y);y+=5}doc.save(`${name}.pdf`)}async function word(){const {Document,Packer,Paragraph,HeadingLevel}=await import("docx");const paragraphs=[new Paragraph({text:artifact.title,heading:HeadingLevel.TITLE}),...artifactText(artifact).split("\n").map(text=>new Paragraph({text}))];download(await Packer.toBlob(new Document({sections:[{children:paragraphs}]})),`${name}.docx`)}function excel(){const escape=(v:string)=>v.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");const html=`<html><meta charset="utf-8"><table>${rows.map(row=>`<tr>${row.map(cell=>`<td>${escape(cell)}</td>`).join("")}</tr>`).join("")}</table></html>`;download(new Blob([html],{type:"application/vnd.ms-excel"}),`${name}.xls`)}return <div className="export-actions"><Button variant="outline" onClick={pdf}><Download/> PDF</Button><Button variant="outline" onClick={word}><Download/> Word</Button>{rows.length>0&&<Button variant="outline" onClick={excel}><Download/> Excel</Button>}</div>}
