"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeftRight, Check, Clock3, Copy, Languages, LoaderCircle, Sparkles, Volume2 } from "lucide-react";
import { api } from "@/lib/api";
import { useAuthStore } from "@/stores/auth-store";
import type { Translation } from "@/types/api";
import { Button } from "@/components/ui/button";

const modes=[["natural","Natural"],["professional","Professional"],["academic","Academic"],["simple","Simple"],["direct","Direct"]];
const languageName=(code:string)=>code==="rw"?"Kinyarwanda":"English";
const delay=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));

export default function TranslatePage(){
  const token=useAuthStore(state=>state.accessToken)!,queryClient=useQueryClient(),typingRun=useRef(0);
  const [source,setSource]=useState<"auto"|"en"|"rw">("auto"),[target,setTarget]=useState<"en"|"rw">("rw"),[mode,setMode]=useState("natural"),[input,setInput]=useState(""),[output,setOutput]=useState(""),[detected,setDetected]=useState<string|null>(null),[typing,setTyping]=useState(false),[copied,setCopied]=useState(false);
  const history=useQuery({queryKey:["translations"],queryFn:()=>api.translations(token)});
  const translate=useMutation({mutationFn:()=>api.translate(input.trim(),source==="auto"?null:source,target,mode,token),onSuccess:result=>{setDetected(result.translation.source_language);typeOutput(result.translation.translated_text);queryClient.invalidateQueries({queryKey:["translations"]})}});
  useEffect(()=>()=>{typingRun.current+=1},[]);
  async function typeOutput(content:string){const run=++typingRun.current;setOutput("");setTyping(true);const step=content.length>2000?12:content.length>800?7:3;for(let i=step;i<content.length;i+=step){if(run!==typingRun.current)return;setOutput(content.slice(0,i));await delay(10)}if(run===typingRun.current){setOutput(content);setTyping(false)}}
  function submit(event:FormEvent){event.preventDefault();if(input.trim()&&!typing)translate.mutate()}
  function swap(){typingRun.current+=1;setTyping(false);const translated=output;if(source==="auto"){setSource(target);setTarget(detected==="rw"?"rw":"en")}else{const previous=source;setSource(target);setTarget(previous)}setInput(translated||input);setOutput(input)}
  async function copy(){if(!output)return;await navigator.clipboard.writeText(output);setCopied(true);setTimeout(()=>setCopied(false),1600)}
  function listen(){if(!output||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(output);utterance.lang=target==="rw"?"rw-RW":"en-US";window.speechSynthesis.speak(utterance)}
  function restore(item:Translation){typingRun.current+=1;setTyping(false);setSource(item.source_language);setTarget(item.target_language);setMode(item.mode);setInput(item.source_text);setOutput(item.translated_text);setDetected(item.source_language)}
  return <section className="translate-page"><header className="translate-head"><div><span className="kicker">BILINGUAL TRANSLATION</span><h1>Meaning,<br/><em>not just words.</em></h1><p>Move naturally between English and Kinyarwanda with automatic detection and context-aware tone.</p></div><div className="translate-mark"><Languages/><span>EN ↔ RW</span></div></header>
    <div className="translate-workspace"><main className="translator-card"><div className="translation-toolbar"><label>From<select value={source} onChange={event=>setSource(event.target.value as "auto"|"en"|"rw")}><option value="auto">Detect automatically</option><option value="en">English</option><option value="rw">Kinyarwanda</option></select></label><Button type="button" variant="ghost" size="icon" onClick={swap} aria-label="Swap languages"><ArrowLeftRight/></Button><label>To<select value={target} onChange={event=>setTarget(event.target.value as "en"|"rw")}><option value="rw">Kinyarwanda</option><option value="en">English</option></select></label></div><div className="tone-picker"><span>Tone</span>{modes.map(([value,label])=><button key={value} type="button" className={mode===value?"active":""} onClick={()=>setMode(value)}>{label}</button>)}</div><form onSubmit={submit}><div className="translation-panels"><section><header><strong>{source==="auto"?(detected?`${languageName(detected)} detected`:"Automatic detection"):languageName(source)}</strong><small>{input.length.toLocaleString()} characters</small></header><textarea value={input} onChange={event=>setInput(event.target.value)} placeholder="Type or paste text in English or Kinyarwanda…" maxLength={100000}/></section><section className="translated-panel"><header><strong>{languageName(target)}</strong><div><button type="button" onClick={listen} aria-label="Listen to translation"><Volume2/></button><button type="button" onClick={copy} aria-label="Copy translation">{copied?<Check/>:<Copy/>}</button></div></header><div className={`translation-output ${typing?"typing":""}`}>{translate.isPending?<span className="translating"><LoaderCircle className="spin"/> EVA is translating meaning and tone…</span>:output||<span className="translation-placeholder">Your translation will appear here for side-by-side review.</span>}</div></section></div><div className="translate-submit"><span>{source==="auto"?"EVA will detect the source language":`${languageName(source)} to ${languageName(target)}`}</span><Button disabled={!input.trim()||translate.isPending||typing}>{translate.isPending?<LoaderCircle className="spin"/>:<Sparkles/>} Translate</Button></div>{translate.error&&<p className="form-error">{translate.error.message}</p>}</form></main>
      <aside className="translation-history"><div><Clock3/><span><strong>Recent translations</strong><small>{history.data?.total||0} saved privately</small></span></div>{history.isLoading&&<p>Loading…</p>}{!history.isLoading&&!history.data?.items.length&&<p className="translation-empty">Your recent translations will appear here.</p>}{history.data?.items.map(item=><button key={item.id} onClick={()=>restore(item)}><span>{item.source_language.toUpperCase()} → {item.target_language.toUpperCase()} · {item.mode}</span><strong>{item.source_text}</strong><small>{new Date(item.created_at).toLocaleString()}</small></button>)}</aside></div>
  </section>
}
